pipeline {
    agent { label 'master' }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/sdeschaepmeester/Devops-POC.git', credentialsId: 'github-creds'
            }
        }
        stage('Build') {
            steps {
                script {
                    docker.image('openjdk:22-jdk-slim').inside {
                        sh 'java -version'
                        // Ajoutez ici des étapes supplémentaires pour le build
                    }
                }
            }
        }
    }
}
