pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Construire l'image Docker
                    sh 'docker build -t backend-app .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    // Arrêter et supprimer le conteneur existant s'il y en a un
                    sh 'docker stop backend-container || true'
                    sh 'docker rm backend-container || true'
                    
                    // Exécuter le nouveau conteneur
                    sh 'docker run -d -p 8080:8080 --name backend-container backend-app'
                }
            }
        }
    }
}
