pipeline {
    agent {
        docker {
            image 'openjdk:22-jdk-slim'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'javac -d bin src/medhead/Main.java'
            }
        }
        stage('Package') {
            steps {
                sh 'jar cvf jar/backend.jar -C bin .'
            }
        }
        stage('Dockerize') {
            steps {
                sh 'docker build -t backend-app .'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'java -jar jar/backend.jar'
            }
        }
    }
}
