name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch !

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java source code
        run: |
          mkdir -p backend/jar
          javac -d backend/jar backend/src/medhead/Main.java
          jar cvf backend/jar/backend.jar -C backend/jar .

      - name: Build Docker image
        run: |
          cd backend
          docker build -t deschaepmeesters/backend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push deschaepmeesters/backend:latest