name: Build, Push, and Deploy Frontend Docker Image

on:
  push:
    branches:
      - main  # Trigger on main branch
    paths:
      - 'frontend/**'  # Trigger when changes inside frontend subfolder

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          cd frontend
          docker build -t deschaepmeesters/frontend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push deschaepmeesters/frontend:latest

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku CLI
        run: heroku auth:token
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Log in to Heroku Container Registry
        run: echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Deploy to Heroku
        run: |
          docker tag deschaepmeesters/frontend:latest registry.heroku.com/medhead-frontend/web
          docker push registry.heroku.com/medhead-frontend/web
          heroku container:release web --app medhead-frontend
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}